code/src/main/java/br/ufes/informatica/marvin/admin/controller/ManagePPGsController.java
package br.ufes.informatica.marvin.admin.controller;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;

import br.ufes.inf.nemo.jbutler.ejb.application.CrudException;
import br.ufes.inf.nemo.jbutler.ejb.application.CrudService;
import br.ufes.inf.nemo.jbutler.ejb.controller.CrudController;
import br.ufes.inf.nemo.jbutler.ejb.controller.PersistentObjectConverterFromId;
import br.ufes.informatica.marvin.core.application.ManageAcademicsService;
import br.ufes.informatica.marvin.core.application.ManageOccupationsService;
import br.ufes.informatica.marvin.core.application.ManagePPGsService;
import br.ufes.informatica.marvin.core.domain.Academic;
import br.ufes.informatica.marvin.core.domain.Occupation;
import br.ufes.informatica.marvin.core.domain.PPG;
import br.ufes.informatica.marvin.core.domain.Role;

@Named
@SessionScoped
public class ManagePPGsController extends CrudController<PPG> {
	private static final long serialVersionUID = 1L;

	@EJB
	private ManagePPGsService managePPGsService;

	@EJB
	private ManageAcademicsService manageAcademicsService;

	@EJB
	private ManageOccupationsService manageOccupationsService;

	private List<Academic> coordinators;

	private Academic selectedAdmin;

	private List<Occupation> listAdmins;

	private List<Occupation> trashAdmins;

	private String typeAdmin;

	@Override
	protected CrudService<PPG> getCrudService() {
		return managePPGsService;
	}

	/** Logger for this class. */
	private static final Logger logger = Logger.getLogger(ManagePPGsController.class.getCanonicalName());

	/**
	 * Path to the folder where the view files (web pages) for this action are
	 * placed.
	 */
	private static final String VIEW_PATH = "/admin/managePPGs/";

	@Override
	protected void initFilters() {
	}

	public Academic getSelectedAdmin() {
		return selectedAdmin;
	}

	public void setSelectedAdmin(Academic selectedAdmin) {
		this.selectedAdmin = selectedAdmin;
	}

	public List<Occupation> getListAdmins() {
		return listAdmins;
	}

	public void setListAdmins(List<Occupation> listAdmins) {
		this.listAdmins = listAdmins;
	}

	public List<Academic> getCoordinators() {
		return coordinators;
	}

	public void setCoordinators(List<Academic> coordinators) {
		this.coordinators = coordinators;
	}

	public String getTypeAdmin() {
		return typeAdmin;
	}

	public void setTypeAdmin(String typeAdmin) {
		this.typeAdmin = typeAdmin;
	}

	public List<Occupation> getTrashAdmins() {
		return trashAdmins;
	}

	public void setTrashAdmins(List<Occupation> trashAdmins) {
		this.trashAdmins = trashAdmins;
	}

	public List<Academic> completeCoordinators(String query) {
		return manageOccupationsService.findAcademicByNameEmail(query);
	}

	public PersistentObjectConverterFromId<Academic> getCoordinatorConverter() {
		return manageOccupationsService.getAcademicConverter();
	}

	public String administrators() {
		setListAdmins(manageOccupationsService.findOccupationsByPPG(selectedEntity.getId()));
		this.trashAdmins = new ArrayList<Occupation>();
		return VIEW_PATH + "formadministrators.xhtml" + "?faces-redirect=" + getFacesRedirect();
	}

	public String savePPG() {
		try {
			managePPGsService.validateCreate(selectedEntity, coordinators);
			managePPGsService.create(selectedEntity);

			List<Occupation> oldCoordinators = manageOccupationsService.findOccupationsByPPG(selectedEntity.getId());

			for (Academic academic : this.coordinators) {

				Occupation occupation = manageOccupationsService.findOccupationByAcademic(academic.getId());

				if (occupation == null) {
					Occupation newOccupation = new Occupation();
					newOccupation.setAcademic(academic);
					newOccupation.setCoordinator(true);
					newOccupation.setSecretary(false);
					newOccupation.setDoctoral_supervisor(false);
					newOccupation.setMember(true);
					newOccupation.setPpg(selectedEntity);
					manageOccupationsService.create(newOccupation);
				} else {
					occupation.setCoordinator(true);
					occupation.setSecretary(false);
					occupation.setDoctoral_supervisor(false);
					occupation.setMember(true);
					occupation.setPpg(selectedEntity);
					manageOccupationsService.update(occupation);

					if (oldCoordinators.contains(occupation)) {
						oldCoordinators.remove(occupation);
					}
				}
			}

			for (Occupation remove : oldCoordinators) {
				manageOccupationsService.delete(remove);
			}

			setCoordinators(null);

			return list();
		} catch (CrudException e) {
			FacesContext context = FacesContext.getCurrentInstance();
			FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_WARN, "Create PPG requested", e.getMessage());
			context.addMessage(null, message);
		}

		return "";

	}

	public String updatePPG() {
		setCoordinators(null);
		if (selectedEntity != null) {
			List<Academic> coordinators = manageOccupationsService.findAcademicsByPPG(selectedEntity.getId());
			setCoordinators(coordinators);
			return update();
		}

		return "";
	}

	public String createPPG() {
		setCoordinators(null);
		return create();
	}

	public String saveAdministrator() {

		Occupation occupation = manageOccupationsService.findOccupationByAcademic(selectedAdmin.getId());

		if (occupation != null) {

			if (typeAdmin.equals("coordinator")) {
				occupation.setSecretary(false);
				occupation.setCoordinator(true);
			} else if (typeAdmin.equals("secretary")) {
				occupation.setSecretary(true);
				occupation.setCoordinator(false);
			}

			manageOccupationsService.update(occupation);

		} else {

			Occupation newOccupation = new Occupation();
			newOccupation.setAcademic(selectedAdmin);
			if (typeAdmin.equals("coordinator")) {
				newOccupation.setSecretary(false);
				newOccupation.setCoordinator(true);
			} else if (typeAdmin.equals("secretary")) {
				newOccupation.setSecretary(true);
				newOccupation.setCoordinator(false);
			}
			newOccupation.setDoctoral_supervisor(false);
			newOccupation.setMember(true);
			newOccupation.setPpg(selectedEntity);
			manageOccupationsService.create(newOccupation);
		}

		setListAdmins(manageOccupationsService.findOccupationsByPPG(selectedEntity.getId()));

		return VIEW_PATH + "formadministrators.xhtml" + "?faces-redirect=" + getFacesRedirect();
	}

	public PersistentObjectConverterFromId<Role> getRoleConverter() {
		return manageAcademicsService.getRoleConverter();
	}

	public void deletePPG() {
		for (PPG delete : trashCan) {
			List<Occupation> list = manageOccupationsService.findOccupationsByPPG(delete.getId());
			for (Occupation occupation : list) {
				manageOccupationsService.delete(occupation);
			}

		}
		delete();
	}

	public String setAdminType(Long id, String type) {
		Occupation occupation = manageOccupationsService.retrieve(id);

		if (occupation != null) {
			if (type.equals("coordinator")) {
				occupation.setSecretary(false);
				occupation.setCoordinator(true);
			} else if (type.equals("secretary")) {
				occupation.setSecretary(true);
				occupation.setCoordinator(false);
			}
			manageOccupationsService.update(occupation);
		}

		setListAdmins(manageOccupationsService.findOccupationsByPPG(selectedEntity.getId()));

		return VIEW_PATH + "formadministrators.xhtml" + "?faces-redirect=" + getFacesRedirect();
	}

	public void trashAdmin(Long id) {
		Occupation occupation = manageOccupationsService.retrieve(id);

		if (occupation == null) {
			logger.log(Level.WARNING, "Method trashAdmin() called, but cant find occupation with id: {0}!", id);
			return;
		}

		trashAdmins.add(occupation);

	}

	public void cancelDeletionAdmin() {
		// Removes all entities from the trash and cancel their deletion.
		logger.log(Level.INFO, "Deletion has been cancelled. Clearing trash can");
		trashAdmins.clear();
	}

	public void deleteAdminPPG() {
		try {
			managePPGsService.validateAdminPPGDelete(selectedEntity, trashAdmins);

			for (Occupation delete : trashAdmins) {
				manageOccupationsService.delete(delete);
			}

			logger.log(Level.INFO, "Deletion of PPG admins was done successfully");
			trashAdmins.clear();

			setListAdmins(manageOccupationsService.findOccupationsByPPG(selectedEntity.getId()));

		} catch (CrudException e) {
			FacesContext context = FacesContext.getCurrentInstance();
			FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_WARN, "Create PPG requested", e.getMessage());
			context.addMessage(null, message);
		}
	}
}

code/src/main/webapp/admin/managePPGs/form.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:adm="http://github.com/adminfaces"
	template="/WEB-INF/templates/template.xhtml">

	<ui:define name="title">
		<h:outputText value="#{msgsAdmin['managePPGs.title.create']}" rendered="#{(! managePPGsController.readOnly) and (managePPGsController.selectedEntity.id == null)}" />
		<h:outputText value="#{msgsAdmin['managePPGs.title.update']}" rendered="#{(! managePPGsController.readOnly) and (managePPGsController.selectedEntity.id != null)}" />
		<h:outputText value="#{msgsAdmin['managePPGs.title.retrieve']}" rendered="#{managePPGsController.readOnly}" />
	</ui:define>

	<ui:define name="description">
		<h:outputText value="#{msgsAdmin['managePPGs.title.create.description']}" rendered="#{(! managePPGsController.readOnly) and (managePPGsController.selectedEntity.id == null)}" />
		<h:outputText value="#{msgsAdmin['managePPGs.title.update.description']}" rendered="#{(! managePPGsController.readOnly) and (managePPGsController.selectedEntity.id != null)}" />
		<h:outputText value="#{msgsAdmin['managePPGs.title.retrieve.description']}" rendered="#{managePPGsController.readOnly}" />
	</ui:define>

	<ui:define name="body">
		<!-- The breadcrumb. -->
		<adm:breadcrumb title="#{msgsAdmin['managePPGs.title']}" link="index.xhtml" />
	
		<!-- The form to be filled with information on the academic. -->
		<ui:decorate template="/WEB-INF/templates/form.xhtml">
			<ui:param name="formName" value="form" /> 
			<ui:param name="formLabel" value="#{msgsAdmin['managePPGs.form.title']}" />
			<p:focus />
			
			<!-- Field: name. -->
			<ui:decorate template="/WEB-INF/templates/formfield.xhtml">
				<ui:param name="fieldName" value="name" />
				<ui:param name="label" value="#{msgsAdmin['managePPGs.field.name']}" />
				<p:inputText id="name" value="#{managePPGsController.selectedEntity.name}" required="true" ></p:inputText>
			</ui:decorate>
			
			<!-- Field: Nationality. -->
			<ui:decorate template="/WEB-INF/templates/formfield.xhtml">
				<ui:param name="fieldName" value="acronym" />
				<ui:param name="label" value="#{msgsAdmin['managePPGs.field.acronym']}" />
				<p:inputText id="acronym" value="#{managePPGsController.selectedEntity.acronym}" required="true" disabled="#{managePPGsController.readOnly}"></p:inputText>
			</ui:decorate>

			<!-- Field: coordinators. -->
			<ui:decorate template="/WEB-INF/templates/formfield.xhtml">
				<ui:param name="fieldName" value="coordinators" />
				<ui:param name="label" value="#{msgsAdmin['managePPGs.field.coordinators']}" />
				<p:autoComplete id="coordinators" required="true" multiple="true" value="#{managePPGsController.coordinators}" completeMethod="#{managePPGsController.completeCoordinators}" var="coordinators" itemLabel="#{coordinators.shortName}" itemValue="#{coordinators}" converter="#{managePPGsController.coordinatorConverter}" forceSelection="true" >
					<p:column>
						<h:outputText value="#{coordinators.shortName}" />
					</p:column>
					<p:column>
						<h:outputText value="#{coordinators.name}" />
					</p:column>
				</p:autoComplete>			
			</ui:decorate>

			<!-- Buttons shown below the form. -->
			<h:panelGroup rendered="#{! managePPGsController.readOnly}">
				<ui:decorate template="/WEB-INF/templates/formbuttonpanel.xhtml">
					<p:commandButton id="cancelButton" action="#{managePPGsController.list}" value="#{msgs['jbutler.crud.button.cancel']}" immediate="true" icon="fa fa-fw fa-close" />
					<p:commandButton id="saveButton" action="#{managePPGsController.savePPG}" value="#{msgs['jbutler.crud.button.save']}" update=":form :messages :info-messages" icon="fa fa-fw fa-save" />
					<p:defaultCommand target="saveButton" />
				</ui:decorate>
			</h:panelGroup>
			<h:panelGroup rendered="#{managePPGsController.readOnly}">
				<ui:decorate template="/WEB-INF/templates/formbuttonpanel.xhtml">
					<p:commandButton id="backButton" action="#{managePPGsController.list}" value="#{msgs['jbutler.crud.button.back']}" immediate="true" icon="fa fa-fw fa-arrow-circle-left" />
				</ui:decorate>
			</h:panelGroup>
		</ui:decorate>		
	</ui:define>
</ui:composition>

code/src/main/webapp/admin/managePPGs/formadministrators.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:adm="http://github.com/adminfaces"
    template="/WEB-INF/templates/template.xhtml">

   <ui:define name="title">
   <h:outputText value="#{msgsAdmin['managePPGs.title.administrators']}" />
</ui:define>

<ui:define name="description">
	<h:outputText value="#{msgsAdmin['managePPGs.title.administrators.description']}" />
</ui:define>

<ui:define name="body" id="bodyAdminstrador">
		<!-- The breadcrumb. -->
		<adm:breadcrumb title="#{msgsAdmin['managePPGs.title']}" link="index.xhtml" />
	
		<!-- The form to be filled with information on the academic. -->
		<ui:decorate template="/WEB-INF/templates/form.xhtml">
			<ui:param name="formName" value="form" /> 
			<ui:param name="formLabel" value="#{msgsAdmin['managePPGs.title.administrators']}" />
			<p:focus />
			
			<!-- Field: coordinators. -->
			<ui:decorate template="/WEB-INF/templates/formfield.xhtml">
				<ui:param name="fieldName" value="typeAdmin" />
				<ui:param name="label" value="#{msgsAdmin['managePPGs.field.typeAdmin']}" />
				<p:selectOneMenu style="width: 300px;" id="typeAdmin" value="#{managePPGsController.typeAdmin}"> 
				    <f:selectItem itemLabel="" itemValue="all"/>
                    <f:selectItem itemLabel="Coordinator" itemValue="coordinator"/>
                    <f:selectItem itemLabel="Secretary" itemValue="secretary"/>
				</p:selectOneMenu> 
			</ui:decorate>
			
			<!-- Field: coordinators. -->
			<ui:decorate template="/WEB-INF/templates/formfield.xhtml">
				<ui:param name="fieldName" value="coordinators" />
				<ui:param name="label" value="#{msgsAdmin['managePPGs.field.coordinators']}" />
				<p:autoComplete style="width: 300px;" id="coordinators" value="#{managePPGsController.selectedAdmin}" completeMethod="#{managePPGsController.completeCoordinators}" var="coordinators" itemLabel="#{coordinators.shortName}" itemValue="#{coordinators}" converter="#{managePPGsController.coordinatorConverter}" forceSelection="true" >
					<p:column>
						<h:outputText value="#{coordinators.name}" />
					</p:column>
					<p:column>
						<h:outputText value="#{coordinators.email}" />
					</p:column>
				</p:autoComplete>
			</ui:decorate>
			<!-- Buttons shown below the form. -->
			<h:panelGroup id="buttonsGroup" >
				<ui:decorate template="/WEB-INF/templates/formbuttonpanel.xhtml">
					<p:commandButton id="cancelButton" action="#{managePPGsController.list}" value="#{msgs['jbutler.crud.button.back']}" immediate="true" icon="fa fa-fw fa-close" />
					<p:commandButton action="#{managePPGsController.saveAdministrator}" value="#{msgsAdmin['managePPGs.button.save']}" update=":form :messages :info-messages" icon="fa fa-fw fa-save" />
				</ui:decorate>
			</h:panelGroup>
		</ui:decorate>		
		<h:form id="formTable">
			<h:panelGroup>
				<p:dataTable
					id="entitiesDataTable"
					widgetVar="listingTable"
					value="#{managePPGsController.listAdmins}" 
					var="entity" 
					rowKey="#{entity.id}"
					rows="#{mmanagePPGsController.maxDataTableRowsPerPage}" 
					rowsPerPageTemplate="#{managePPGsController.halfMaxDataTableRowsPerPage},#{managePPGsController.maxDataTableRowsPerPage},#{managePPGsController.doubleMaxDataTableRowsPerPage}"
					lazy="true" 
					paginator="true" 
					paginatorPosition="bottom" 
					emptyMessage="#{msgsAdmin['managePPGs.occupation.noEntities']}">
					
					<p:column headerText="#{msgsAdmin['managePPGs.occupation.name']}">
						<h:outputText value="#{entity.academic.getName()}" />
					</p:column>
					
					<p:column headerText="#{msgsAdmin['managePPGs.occupation.ppg']}">
						<h:outputText value="#{entity.ppg == null ? 'IS NOT ASSOCIATED' :  entity.ppg.acronym}" />
					</p:column>
	
					<p:column style="text-align: center;" headerText="#{msgsAdmin['managePPGs.occupation.coordinator']}">
						<p:commandButton rendered="#{entity.secretary}" action="#{managePPGsController.setAdminType(entity.id, 'coordinator')}" value="#{'NO'}" />
						<p:commandButton rendered="#{entity.coordinator}" action="#{managePPGsController.setAdminType(entity.id, 'secretary')}" value="#{'YES'}" />
					</p:column>
					
					<p:column style="text-align: center;" headerText="#{msgsAdmin['managePPGs.occupation.secretary']}">
						<p:commandButton rendered="#{entity.secretary}" action="#{managePPGsController.setAdminType(entity.id, 'coordinator')}" value="#{'YES'}" />
						<p:commandButton rendered="#{entity.coordinator}" action="#{managePPGsController.setAdminType(entity.id, 'secretary')}" value="#{'NO'}" />
					</p:column>
					
					<p:column style="text-align: center;" headerText="#{msgs['jbutler.crud.button.delete']}">
						<p:commandButton action="#{managePPGsController.trashAdmin(entity.id)}" value="#{msgs['jbutler.crud.button.delete']}" immediate="true" icon="fa fa-trash" update=":formTrash:trashGroup" />
					</p:column>
					<p:ajax event="rowSelect" update=":form:buttonsGroup" />
				</p:dataTable>	
					
			</h:panelGroup>		
						
		
		</h:form>
		<h:form id="formTrash">
			<h:panelGroup id="trashGroup">
				<p:panel id="trashPanel" header="#{msgs['jbutler.crud.text.trashHeader']}" rendered="#{not empty managePPGsController.trashAdmins}" style="margin-top: 20px">
					<p:dataList value="#{managePPGsController.trashAdmins}" var="entity" type="ordered">
		            	#{entity.academic.getName()} (#{entity.secretary ? 'Secretary' : 'Coordinator'})
		            </p:dataList>
					<ui:decorate template="/WEB-INF/templates/formbuttonpanel.xhtml">
						<p:commandButton action="#{managePPGsController.cancelDeletionAdmin}" value="#{msgs['jbutler.crud.button.cancelDeletion']}" icon="fa fa-fw fa-close" process="@this" update=":formTrash:trashGroup"/>
						<p:commandButton action="#{managePPGsController.deleteAdminPPG}" value="#{msgs['jbutler.crud.button.confirmDeletion']}" icon="fa fa-fw fa-trash-o" process="@this" update=":formTrash :formTable" />
					</ui:decorate>
				</p:panel>
			</h:panelGroup>
		</h:form>
		
	</ui:define>
</ui:composition>

code/src/main/webapp/admin/managePPGs/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:adm="http://github.com/adminfaces"
    template="/WEB-INF/templates/template.xhtml">

    <ui:define name="title">
	<h:outputText value="#{msgsAdmin['managePPGs.title']}" />
</ui:define>

<ui:define name="description">
	<h:outputText value="#{msgsAdmin['managePPGs.title.description']}" />
</ui:define>

<ui:define name="body">
	<adm:breadcrumb link="/core/managePPGs/index" title="#{msgsAdmin['managePPGs.title']}" />
	<h:form id="listingForm">
		<p:dataTable id="entitiesDataTable" var="entity" value="#{managePPGsController.lazyEntities}"
			selection="#{managePPGsController.selectedEntity}" selectionMode="single" paginator="true"
			rows="#{managePPGsController.maxDataTableRowsPerPage}"
			paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
			rowsPerPageTemplate="#{managePPGsController.halfMaxDataTableRowsPerPage},#{managePPGsController.maxDataTableRowsPerPage},#{managePPGsController.doubleMaxDataTableRowsPerPage}"
			lazy="true" paginatorPosition="bottom" emptyMessage="#{msgsAdmin['managePPGs.text.noEntities']}">
			<p:ajax event="rowSelect" update="buttonsGroup" />
			<p:ajax event="rowUnselect" update="buttonsGroup" />
			<p:column headerText="#{msgsAdmin['managePPGs.field.id']}">
				<h:outputText value="#{entity.id}" />
			</p:column>
			<p:column headerText="#{msgsAdmin['managePPGs.field.name']}">
				<h:outputText value="#{entity.name}" />
			</p:column>
			<p:column headerText="#{msgsAdmin['managePPGs.field.acronym']}">
				<h:outputText value="#{entity.acronym}" />
			</p:column>
			<f:facet name="footer">
				<h:panelGroup id="buttonsGroup">
					<p:commandButton action="#{managePPGsController.createPPG}" icon="fa fa-plus" value="#{msgs['jbutler.crud.button.create']}" />
					<p:commandButton action="#{managePPGsController.administrators}" icon="fa fa-search" value="#{msgsAdmin['managePPGs.button.administrators']}" disabled="#{managePPGsController.selectedEntity == null}" />
					<p:commandButton action="#{managePPGsController.updatePPG}" icon="fa fa-edit" value="#{msgs['jbutler.crud.button.update']}"
						disabled="#{managePPGsController.selectedEntity == null}" />
					<p:commandButton action="#{managePPGsController.trash}" icon="fa fa-trash" value="#{msgs['jbutler.crud.button.delete']}" process="@this" update="trashGroup"
						disabled="#{managePPGsController.selectedEntity == null}" />
				</h:panelGroup>
				<!-- The trash panel: shows entities that have been selected for deletion. -->
				<h:panelGroup id="trashGroup">
					<p:panel id="trashPanel" header="#{msgs['jbutler.crud.text.trashHeader']}" rendered="#{not empty managePPGsController.trashCan}" style="margin-top: 20px">
						<p:dataList value="#{managePPGsController.trashCan}" var="entity" type="ordered">
			            	#{entity.name} (#{entity.acronym})
			            </p:dataList>
						<ui:decorate template="/WEB-INF/templates/formbuttonpanel.xhtml">
							<p:commandButton action="#{managePPGsController.cancelDeletion}" value="#{msgs['jbutler.crud.button.cancelDeletion']}" icon="fa fa-fw fa-close" process="@this" update=":listingForm" />
							<p:commandButton action="#{managePPGsController.deletePPG}" value="#{msgs['jbutler.crud.button.confirmDeletion']}" icon="fa fa-fw fa-trash-o" process="@this" update=":messages :info-messages :listingForm" />
						</ui:decorate>
					</p:panel>
				</h:panelGroup>
			</f:facet>
		</p:dataTable>
	</h:form>
</ui:define>

</ui:composition>